data = [
    {"name": "Cristiano Ronaldo", "follower_count": 600, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": 500, "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": 430, "description": "Musician", "country": "USA"},
    {"name": "Kylie Jenner", "follower_count": 400, "description": "Entrepreneur", "country": "USA"},
    {"name": "Dwayne Johnson", "follower_count": 390, "description": "Actor", "country": "USA"},
    {"name": "Ariana Grande", "follower_count": 380, "description": "Musician", "country": "USA"},
    {"name": "Kim Kardashian", "follower_count": 360, "description": "TV Personality", "country": "USA"},
    {"name": "Beyonce", "follower_count": 320, "description": "Musician", "country": "USA"},
    {"name": "Khloe Kardashian", "follower_count": 310, "description": "TV Personality", "country": "USA"},
    {"name": "Justin Bieber", "follower_count": 290, "description": "Musician", "country": "Canada"},
    {"name": "Taylor Swift", "follower_count": 280, "description": "Musician", "country": "USA"},
    {"name": "Kendall Jenner", "follower_count": 290, "description": "Model", "country": "USA"},
    {"name": "Virat Kohli", "follower_count": 270, "description": "Cricketer", "country": "India"},
    {"name": "Nicki Minaj", "follower_count": 230, "description": "Musician", "country": "USA"},
    {"name": "Neymar Jr", "follower_count": 220, "description": "Footballer", "country": "Brazil"},
    {"name": "Katy Perry", "follower_count": 200, "description": "Musician", "country": "USA"},
    {"name": "Zendaya", "follower_count": 190, "description": "Actor", "country": "USA"},
    {"name": "Kevin Hart", "follower_count": 180, "description": "Comedian", "country": "USA"},
    {"name": "Miley Cyrus", "follower_count": 170, "description": "Musician", "country": "USA"},
    {"name": "Rihanna", "follower_count": 150, "description": "Musician", "country": "Barbados"},

    {"name": "LeBron James", "follower_count": 160, "description": "Basketball Player", "country": "USA"},
    {"name": "Drake", "follower_count": 145, "description": "Musician", "country": "Canada"},
    {"name": "Billie Eilish", "follower_count": 120, "description": "Musician", "country": "USA"},
    {"name": "Shakira", "follower_count": 110, "description": "Musician", "country": "Colombia"},
    {"name": "Chris Hemsworth", "follower_count": 120, "description": "Actor", "country": "Australia"},
    {"name": "Robert Downey Jr", "follower_count": 100, "description": "Actor", "country": "USA"},
    {"name": "Emma Watson", "follower_count": 75, "description": "Actor", "country": "UK"},
    {"name": "Tom Holland", "follower_count": 70, "description": "Actor", "country": "UK"},
    {"name": "Will Smith", "follower_count": 80, "description": "Actor", "country": "USA"},
    {"name": "Gal Gadot", "follower_count": 90, "description": "Actor", "country": "Israel"},

    {"name": "Shawn Mendes", "follower_count": 70, "description": "Musician", "country": "Canada"},
    {"name": "Ed Sheeran", "follower_count": 50, "description": "Musician", "country": "UK"},
    {"name": "Bruno Mars", "follower_count": 55, "description": "Musician", "country": "USA"},
    {"name": "Bad Bunny", "follower_count": 90, "description": "Musician", "country": "Puerto Rico"},
    {"name": "Post Malone", "follower_count": 60, "description": "Musician", "country": "USA"},
    {"name": "Camila Cabello", "follower_count": 65, "description": "Musician", "country": "USA"},
    {"name": "Cardi B", "follower_count": 170, "description": "Musician", "country": "USA"},
    {"name": "Doja Cat", "follower_count": 75, "description": "Musician", "country": "USA"},
    {"name": "Snoop Dogg", "follower_count": 85, "description": "Musician", "country": "USA"},
    {"name": "Eminem", "follower_count": 45, "description": "Rapper", "country": "USA"},

    {"name": "Adele", "follower_count": 55, "description": "Musician", "country": "UK"},
    {"name": "The Weeknd", "follower_count": 110, "description": "Musician", "country": "Canada"},
    {"name": "Jason Derulo", "follower_count": 60, "description": "Musician", "country": "USA"},
    {"name": "Kylian Mbappe", "follower_count": 110, "description": "Footballer", "country": "France"},
    {"name": "Erling Haaland", "follower_count": 40, "description": "Footballer", "country": "Norway"},
    {"name": "David Beckham", "follower_count": 85, "description": "Footballer", "country": "UK"},
    {"name": "Zlatan Ibrahimovic", "follower_count": 60, "description": "Footballer", "country": "Sweden"},
    {"name": "Lewis Hamilton", "follower_count": 35, "description": "Racing Driver", "country": "UK"},
    {"name": "Conor McGregor", "follower_count": 45, "description": "MMA Fighter", "country": "Ireland"},
    {"name": "Serena Williams", "follower_count": 20, "description": "Tennis Player", "country": "USA"},
]
print(data)
